---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_facts ['distribution'] == "RedHat"

  - name: installing apache package
    dnf:
      name: httpd
      state: latest
    when: ansible_facts ['distribution'] == "RedHat"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_facts ['distribution'] == "RedHat"
