---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    dnf:
#      update_cache: true

  - name: Install Apache package
    dnf:
      name: httpd
      state: absent

  - name: add php support for apache
    dnf:
      name: php
      state: absent
