---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Red Hat)
    package:
      update_only: yes
      update_cache: yes
    when: ansible_facts ['distribution'] == "RedHat"

- hosts: web_servers
  become: true
  tasks:

  - name: installing apache and php packages
    dnf:
      name:
        - httpd
        - php
      state: latest

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      dnf:
        name: mariadb
        state: latest

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      dnf:
        name: samba
        state: latest
